# Generated by Django 5.1.3 on 2024-11-27 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_directivo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profesor',
            new_name='Profesores',
        ),
    ]
