# Generated by Django 5.1.3 on 2024-12-09 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_rename_profesor_profesores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiantes',
            old_name='año',
            new_name='ano',
        ),
    ]
