# Generated by Django 5.1.3 on 2024-12-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_rename_año_estudiantes_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='inasistencias',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
